### ISSUE TITLE
versioneye plugin (version 2.0.0) does not work behind firewall / proxy

### ISSUE THREAD

**Issue by hakan42** [versioneye/versioneye_maven_plugin#12]
Running versioneye:create in a network which requires outgoing http(s) requests to go through a company proxy fails:

```
[ERROR] Failed to execute goal com.versioneye:versioneye-maven-plugin:2.0.0:create (default-cli) on project xing-sync: Oh no! Something went wrong :-( Get in touch with the Version
Eye guys and give them feedback.You find them on Twitter at https//twitter.com/VersionEye. Connection refused: connect -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.versioneye:versioneye-maven-plugin:2.0.0:create (default-cli) on project xing-sync: Oh no! Someth
ing went wrong :-( Get in touch with the VersionEye guys and give them feedback.You find them on Twitter at https//twitter.com/VersionEye.
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:217)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
...
Caused by: java.net.ConnectException: Connection refused: connect
        at java.net.DualStackPlainSocketImpl.connect0(Native Method)
        at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
```

The same works o.k. when direct access to the internet is used. In this case, the proxy settings configured in maven settings.xml should be honored.

**Comment by reiz** [comment]
@hakan42 @alexnb Does this problem still exist? 

By the way. Why not using the newest version of the plugin, which 3.7.0 now ;)

**Comment by hakan42** [comment]
I am not working behind that proxy anymore so I have no good way to test this.

So, from my point of view, the ticket could be closed, and if and when a similar issue happens, a fresh one could be opened.

**Comment by reiz** [comment]
All right. I tested version 3.6.0 with a proxy 2 weeks ago. That was from the intranet of a big insurance company and that worked. That's why I close this ticket :)
