### ISSUE TITLE
missing a goal to list outdated dependencies?

### ISSUE THREAD

**Issue by jillesvangurp** [versioneye/versioneye_maven_plugin#41]
versioneye:create tells me stuff is outdated but not what

versioneye:report would be a nice way to compare current dependencies with latest serverside dependencies.

**Comment by reiz** [comment]
That's a good idea :+1:

**Comment by reiz** [comment]
@jillesvangurp I just changed the output. Now `mvn versioneye:create` and `mvn versioneye:update` will output the out-dated dependencies like in the image here. 

![screen shot 2016-02-26 at 21 44 57](https://cloud.githubusercontent.com/assets/652130/13364949/76ff3b08-dcd2-11e5-9095-7d2997a46d12.png)

Good enough?

**Comment by jillesvangurp** [comment]
Awesome. will give it a try soon.

**Comment by reiz** [comment]
Thx :)

**Comment by reiz** [comment]
I close this because it's used already by many other users and it seems to work for them ;)
