### ISSUE TITLE
versioneye-maven-plugin is not tracked properly at versioneye.com :)

### ISSUE THREAD

**Issue by hakan42** [versioneye/versioneye_maven_plugin#45]
The search query:

https://www.versioneye.com/search?q=versioneye-maven-plugin

shows only 3.5.1 as the newest version, whereas we already have 3.7.0 :smiling_imp:

**Comment by reiz** [comment]
It works :) 

https://www.versioneye.com/search?q=versioneye-maven-plugin

**Comment by reiz** [comment]
We rely on the maven index from Maven Central. Unfortunately that is not updated every day!
