### ISSUE TITLE
Project Id stored in ~/.m2/versioneye.properties

### ISSUE THREAD

**Issue by bindul** [versioneye/versioneye_maven_plugin#48]
When you run mvn com.versioneye:versioneye-maven-plugin:create at the root of a multi module project with minimal configuration in the pom.xml (apiKey, organisation, team) the versioneye.properties file is created under ~/.m2/versioneye.properties with the last project created listed there, rather than versioneye.properties in the project source root.

**Comment by reiz** [comment]
@bindul This was fixed with the [3.9.1](https://github.com/versioneye/versioneye_maven_plugin/releases/tag/3.9.1) release. Please try again with version 3.9.1 and confirm that it works for you.
