### ISSUE TITLE
Unknown license on Versioneye for plugin

### ISSUE THREAD

**Issue by bindul** [versioneye/versioneye_maven_plugin#49]
Not sure if this is an issue with the plugin or server side at VersionEye; but version 3.9.0 of the plugin on VersionEye: [versioneye-maven-plugin : 3.9.0](https://www.versioneye.com/java/com.versioneye:versioneye-maven-plugin/3.9.0) is showing License type **UNKNOWN** and that the *Current* version of the plugin is **3.7.0**, not **3.9.0**.

**Comment by reiz** [comment]
Hi @bindul That was a temporary issue. The VersionEye DB is feeded by the maven index on MVN central. Unfortunately that is not updated every day. That's why there can be some delay. But it's synced now. Please see here: https://www.versioneye.com/java/com.versioneye:versioneye-maven-plugin/3.9.1.
