### ISSUE TITLE
Range support

### ISSUE THREAD

**Issue by overheadhunter** [versioneye/versioneye_maven_plugin#51]
Hi,

I've already created an issue about [version ranges](https://books.sonatype.com/mvnref-book/reference/pom-relationships-sect-project-dependencies.html#pom-relationships-sect-version-ranges) on Jira [228](https://bitbucket.org/versioneye/versioneye/issues/228) which seems to be resolved. However I still experience the same issue (just tried it with this plugin):

I have declared the following dependency:

```
<dependency>
	<groupId>io.reactivex</groupId>
	<artifactId>rxjava</artifactId>
	<version>[1.1.0,]</version>
</dependency>
```

Maven correctly resolves this to `1.1.6`, which is inside the declared range. However versioneye tells me:

```
[INFO] Outdated: 4
[INFO]  - io.reactivex/rxjava:1.1.0, -> 1.1.6
[INFO]  - ...
```

Neither is there such a version `1.1.0,` nor am I using it.

I think this is still a bug. Or am I missing some config option here?

Thanks and keep up the great work!

**Comment by reiz** [comment]
Thanks for reporting it. I will double check it.

**Comment by reiz** [comment]
@overheadhunter as a quick workaround you could run this command on the running container: 

```
docker exec -it tasks /app/init_enterprise.sh
```

That assumes that ALL VersionEye containers are up and running successfully.

**Comment by reiz** [comment]
@overheadhunter I just tried by myself and I can reproduce it. Currently working on a fix.

**Comment by reiz** [comment]
@overheadhunter I found out that your version expression is a bit buggy. Instead of `[1.1.0,]` it should be `[1.1.0,)`. As soon I tried it with `[1.1.0,)` it worked for me.

**Comment by overheadhunter** [comment]
Allright, thanks for the update!
