### ISSUE TITLE
Failed to delete project and update project

### ISSUE THREAD

**Issue by Neola** [versioneye/versioneye_maven_plugin#56]
hi,
I use "mvn versioneye:create" create a project https://www.versioneye.com/user/projects/579efaf1603ea400100516a9,
and also the project_id added into ~/.m2/versioneye.properties
-----
# Properties for https://www.VersionEye.com
#Mon Aug 01 15:35:04 CST 2016
project_id=579efaf1603ea400100516a9
----------

but I run "mvn versioneye:delete or mvn versioneye:update", below error happened,
**[INFO] .
[ERROR] versioneye.properties found but without project_id! Read the instructions at https://github.com/versioneye/versioneye_maven_plugin
org.apache.maven.plugin.MojoExecutionException: versioneye.properties found but without project_id! Read the instructions at https://github.com/versioneye/versioneye_maven_plugin**

I am sure the the project_id exist in versioneye.properties.
could you help on this?

**Comment by reiz** [comment]
Hi @Neola. If you are using 

```
mvn versioneye:create
```

then that creates a `versioneye.properties` file in your src directory and it also writes the project_id into that file. You don't have to do anything manually for that. Can you please run this command in your src directory: 

```
grep "versioneye.properties" -r *
```

And let me how the output looks like?

**Comment by reiz** [comment]
I just published a new version of the Plugin to MVN Central and updated the server code. This problem is solved now.
