### ISSUE TITLE
skipScopes does not work when transitiveDependencies is true

### ISSUE THREAD

**Issue by jcgjunge** [versioneye/versioneye_maven_plugin#60]
The option to skip certain (_skipScopes_) scopes is not possible when setting the option _transitiveDependencies_ is set to true.

To enable versioneye to create a correct report of what a deployable (ear, war etc.) contains of third party products, the combination of _transitiveDependencies_ set to true and _skipScopes_ set to _test,provided..._ is needed.

**Comment by reiz** [comment]
@jcgjunge You are right. Will work on this next week.

**Comment by kyuff** [comment]
Hey @reiz 

Take a look at this GIST: https://gist.github.com/kyuff/bdbf7c2505b6b5235808b80e40cff682

By using this method, it becomes muct easier to work with the dependencies in a Maven Mojo. It shows how to use a group filter, but you could do the same mechanism to create a scope filter as well.

**Comment by jcgjunge** [comment]
Is there any progress on this issue?

**Comment by reiz** [comment]
@jcgjunge @kyuff I can work on this issue next week on Wednesday.

**Comment by reiz** [comment]
@jcgjunge @kyuff Now the new behaviour is that with transitiveDependencies true only RUNTIME dependencies are send to the server. That means dependencies with scope TEST & PROVIDED are ignored. Does that work for you?

**Comment by kyuff** [comment]
@jcgjunge can you close this issue, as the project is not active?
