### ISSUE TITLE
Change default bindings of goals

### ISSUE THREAD

**Issue by rafalwrzeszcz** [versioneye/versioneye_maven_plugin#62]
Currently all MOJOs are bound to `PROCESS_SOURCES` phase, which is I think both ineffective (I don't want it to be executed every time I recompile my project locally or run unit test few times in a row to verify results) and misleading (I wouldn't say checking license whitelist has anything to do with processing source code).

I propose to move:
- `LicenseCheckMojo` -> `VERIFY`
- `SecurityAndLicenseCheckMojo` -> `VERIFY`
- `SecurityCheckMojo` -> `VERIFY`
- `UpdateMojo` -> `PACKAGE`

**Comment by reiz** [comment]
@rafalwrzeszcz Makes sense.
