### ISSUE TITLE
Plugins ignored in projects without Maven dependencies

### ISSUE THREAD

**Issue by freemanjp** [versioneye/versioneye_maven_plugin#66]
If you have a project with no Maven dependencies specified, but with plugins specified (e.g. a project for a Maven archetype), the plugins are ignored and 0 dependencies are uploaded to VersionEye.

Expected behaviour: plugin details are uploaded as VersionEye dependencies even for projects without Maven dependencies.

**Comment by reiz** [comment]
@freemanjp Many Thanks for the pull request. I will release a new version this week and push it to Maven Central.
