### ISSUE TITLE
SSL/TLS intercept proxy

### ISSUE THREAD

**Issue by JOpsDev** [versioneye/versioneye_maven_plugin#69]
**Problem:** 
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building wardemo 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- versioneye-maven-plugin:3.11.0:create (default-cli) @ wardemo ---
[INFO] File C:\Users\tfrech/.m2/versioneye.properties does not exist
[INFO] File C:\Users\tfrech/.m2/versioneye.properties does not exist
[INFO] File C:\Users\tfrech/.m2/versioneye.properties does not exist
[INFO] File C:\Users\tfrech/.m2/versioneye.properties does not exist
[INFO] .
[INFO] Starting to upload dependencies. This can take a couple seconds ... 
[INFO] .
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.316 s
[INFO] Finished at: 2016-11-23T11:39:20+01:00
[INFO] Final Memory: 12M/29M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.versioneye:versioneye-maven-plugin:3.11.0:create (default-cli) on project wardemo: Oh no! Something went wrong :-( Get in touch with the VersionEye guys and give them feedback.You find them on Twitter at https//twitter.com/VersionEye. sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Java used:**
jdk-8u74-windows-i586

**Solution:**
Has to import the DST Root CA X3 certificate (which signed the Let's Encrypt Cert) into cacerts of the JDK.
Should be part of the FAQ or buy a different certificate for the website, please.

**Comment by cdeszaq** [comment]
I'm running into the same issue. Is there a workaround until this is fixed, and if so, detailed steps would be much appreciated!

**Comment by reiz** [comment]
VersionEye.com is using an SSL certificate from [LetsEncrypt](https://letsencrypt.org/). This issue occurs with older versions of the JVM. The LetsEncrypt certs are shipped with Java 8u101 and higher. Please upgrade your JVM to 8u101 or higher. That will fix the issue.
