### ISSUE TITLE
Proxy Authentication Failed

### ISSUE THREAD

**Issue by polarctos** [versioneye/versioneye_maven_plugin#80]
I am behind a corporate proxy that needs authentication, however the version eye plugin does not send the authentication header, even tough it gets the HTTP status 407 back.

```
    CONNECT www.versioneye.com:443 HTTP/1.1
    Host: www.versioneye.com:443
    Proxy-Connection: Keep-Alive
    User-Agent: Apache-HttpClient/4.5.3 (Java/1.8.0_121)
	
    HTTP/1.1 407 Proxy Authentication Required
    Proxy-Authenticate: BASIC realm="Company_Login"
    Cache-Control: no-cache
    Pragma: no-cache
    Content-Type: text/html; charset=utf-8
    Proxy-Connection: close
    Connection: close
    Content-Length: 1283
```

Correct would be another CONNECT request containing e.g. this header, that then leads to success and the TLS handshake afterwards:
```
    ...
    Proxy-Authorization: Basic dXNlcjpwYXNzd29yZA==

    HTTP/1.1 200 Connection established
```

**Comment by reiz** [comment]
I will double check this. Until then please set the proxy via the command line as Maven options like this: 

```
mvn -DproxySet=true -DproxyHost=myproxy.com -DproxyPort=3128 versioneye:update
```
Let me know if this workaround works for you.

**Comment by reiz** [comment]
@polarctos This is fixed now. Version 3.11.4 is published on Maven Central. Please use the VersionEye Maven Plugin 3.11.4. If the issue still exists for you then please re open this ticket.

**Comment by polarctos** [comment]
Thanks a lot!
Version 3.11.4 now works with our proxy authentication.
